import Head from 'next/head'
import Navigation from '../components/Navigation'
import Footer from '../components/Footer'

export default function Layout({ children }) {
    return (
        <div className='app-wrapper'>
            <Head>
                <title>Liefermax - Your Delivery Service</title>
                <meta name="description" content="Generated by virtualdev.de" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <div className="container mb-1">
                {children}
            </div>
            <Footer />
        </div>
    )
}
